name: Publish Release

on: workflow_dispatch # only manual trigger for release creation is allowed

jobs:
  build_tag_repo:
#    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B verify
      - name: Create release tag in GIT
        id: version_update
        uses: fred4jupiter/maven-version-update-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print release version
        run: "echo 'New release Version: ${{steps.version_update.outputs.release-version}}'"