name: Version Update
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Update version
      id: version_update
      uses: fred4jupiter/maven-version-update-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Print release version
      run: "echo 'New Version: ${{steps.version_update.outputs.release-version}}'"
      
    - name: Print next development version
      run: "echo 'New Version: ${{steps.version_update.outputs.next-develop-version}}'"
      