name: Version Update
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest Commit
      id: version_update
      uses: fred4jupiter/maven-version-update-action
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Print release version
      run: "echo 'New Version: ${{steps.version_update.outputs.release-version}}'"
    - name: Print next development version
      run: "echo 'New Version: ${{steps.version_update.outputs.next-develop-version}}'"